export const CREATE_INSTANCE          = 'CREATE_INSTANCE';
export const UPDATE_INSTANCE          = 'UPDATE_INSTANCE';
export const DELETE_INSTANCE          = 'DELETE_INSTANCE';
export const FETCH_ALL_INSTANCE       = 'FETCH_ALL_INSTANCE';
export const FETCH_BY_SEARCH_INSTANCE = 'FETCH_BY_SEARCH_INSTANCE';
export const FETCH_POST_INSTANCE      = 'FETCH_POST_INSTANCE';
export const START_LOADING_INSTANCE   = 'START_LOADING_INSTANCE';
export const END_LOADING_INSTANCE     = 'END_LOADING_INSTANCE';
export const LIKE_INSTANCE            = 'LIKE_INSTANCE';
export const AUTH_INSTANCE            = 'AUTH_INSTANCE';
export const LOGIN_INSTANCE           = 'LOGIN_INSTANCE';
export const LOGOUT_INSTANCE          = 'LOGOUT_INSTANCE';

